name: CI Commons

on:
  push:
  pull:
    branches:
      - 'main'
      - 'dev/*'
    paths:
      - 'libs/commons/**'

jobs:
  maven:
    name: Maven Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Cache Depdendencies
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 17
      - name: Test
        run: mvn clean test --projects :commons --also-make --threads=2 --batch-mode